  quarkus:
    swagger-ui:
      always-include: true
    log:
      level: INFO
    http:
      port: 8127
      cors:
        ~: true

    datasource:
      db-kind: mysql
      username: root
      password: ""
      jdbc:
        url: jdbc:mysql://localhost:3306/toko
    hibernate-orm:
      database:
        generation:
          ~: none
