quarkus:
  swagger-ui:
    always-include: true
  log:
    level: INFO
  http:
    port: 8127
    cors:
      ~: true
      origins: http://localhost:8127,http://localhost:8127/q/swagger-ui
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, OPTIONS, POST

  datasource:
    db-kind: mysql
    username: root
    password: ""
    jdbc:
      url: jdbc:mysql://localhost:3306/toko
  hibernate-orm:
    database:
      generation:
        ~: none
